eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      routes:
      - id: stock-service
        uri: http://localhost:8081
        predicates:
        - Path=/api/v1.0/**
      - id: user-service
        uri: http://localhost:8082
        predicates:
        - Path=/auth/v1/**, /api/v1/**
